
CREATE OR REPLACE PROCEDURE OTIMIZA.PLIBERA_PDV_COM_OTM (PI_SESSAO IN NUMBER,
												 PI_EMPRESA IN VARCHAR2,
												 PI_PEDIDO IN VARCHAR2,
												 PI_SITUACAOF IN VARCHAR2,
												 PI_SITUACAOC IN VARCHAR2,
												 PI_DIVISAO IN NUMBER,
												 PI_REGIAO IN NUMBER,
												 PI_SUPERVISOR IN NUMBER,
												 PI_REPRESENTANTE IN NUMBER,
												 pi_campo_novo in number) IS

	PRAGMA AUTONOMOUS_TRANSACTION;

	 QUERY VARCHAR2(20000);
BEGIN
	
	
		QUERY :=	'SELECT ' || PI_SESSAO || ',
					TPEDIDOS_VENDA.ID,
 					TEMPRESAS.COD_EMP,
					TPEDIDOS_VENDA.SIT_PDV_FIN,
			 	    TPEDIDOS_VENDA.SIT_PDV_COM ,
			 	    TPEDIDOS_VENDA.NUM_PEDIDO,
					TCLIENTES.ID CLIENTE_ID,
			 	    TCLIENTES.COD_CLI || '' - '' || TCLIENTES.DESCRICAO CLIENTE,
			 	    --NVL(otm_formata(TESTABELECIMENTOS.CNPJ,''CNPJ'',''F''),otm_formata(TESTABELECIMENTOS.CPF ,''CPF'',''F'')) CNPJ_CPF,
					CASE 
						WHEN LENGTH(TESTABELECIMENTOS.CNPJ) < 14
							THEN LPAD(TO_CHAR( TESTABELECIMENTOS.CNPJ ),14,0)
						WHEN LENGTH(TESTABELECIMENTOS.CNPJ) >= 14
							THEN TO_CHAR(TESTABELECIMENTOS.CNPJ)
				    END AS CNPJ,
					TREPRESENTANTES.ID REP_ID,
			 	    TREPRESENTANTES.COD_REP || '' - '' || TREPRESENTANTES.DESCRICAO REPRESENTANTE,
			 	    TCOND_PAGTOS.COD_CDPG||'' - ''||TCOND_PAGTOS.DESCRICAO AS COND_PAGTO,
					TPEDIDOS_VENDA.VLR_LIQ VALOR_TOTAL,
					TPORTADORES.ID,
					TPORTADORES.COD_POR || '' - '' || TPORTADORES.DESCRICAO,
					''SUFRAMA'',
					''SIMPLES'',
					''ENDEREÇO'',
					TPEDIDOS_VENDA.DT_EMIS DATA_EMISSAO,
					TPEDIDOS_VENDA.DT_ENTREGA DATA_ENTREGA,
					DECODE(TPEDIDOS_VENDA.FIRME, 1, ''S'',0 , ''N'') AS FIRME,
					SYSDATE,
					TDIVISOES_VENDAS.ID,
					TDIVISOES_VENDAS.DESCRICAO "DIV_VENDA",
					TTIPOS_NF.ID,
					TTIPOS_NF.COD_TP_NF || '' - '' || TTIPOS_NF.DESCRICAO "TP_NF",
					TPEDIDOS_VENDA.TP_FRETE 
			  FROM FOCCO3I.TPEDIDOS_VENDA TPEDIDOS_VENDA,
			  	   FOCCO3I.TCLIENTES TCLIENTES,
			  	   FOCCO3I.TESTABELECIMENTOS TESTABELECIMENTOS,
			  	   FOCCO3I.TREPRESENTANTES TREPRESENTANTES,
			  	   FOCCO3I.TCOND_PAGTOS TCOND_PAGTOS,
			  	   FOCCO3I.TREGIOES TREGIOES,
			 	   FOCCO3I.TREP_REGIAO TREP_REGIAO,
			 	   FOCCO3I.TEMPRESAS TEMPRESAS,
			 	   FOCCO3I.TDIVISOES_VENDAS TDIVISOES_VENDAS,
				   FOCCO3I.TREP_HIERARQUIA TREP_HIERARQUIA,
			 	   FOCCO3I.TEMP_REP TEMP_REP,
			 	   FOCCO3I.TREPRESENTANTES TREPRESENTANTES_COORD,
			 	   FOCCO3I.TCAT_REP TCAT_REP,
				   FOCCO3I.TTIPOS_NF TTIPOS_NF,
				   FOCCO3I.TPORTADORES  
			 WHERE TCLIENTES.ID = TPEDIDOS_VENDA.CLI_ID 
			   AND TCLIENTES.EST_ID_FAT = TESTABELECIMENTOS.ID
			   AND TREPRESENTANTES.ID = TPEDIDOS_VENDA.REP_ID
			   AND TPEDIDOS_VENDA.CDPG_ID = TCOND_PAGTOS.ID
			   AND TREGIOES.ID = TREP_REGIAO.REG_ID
			   AND TREPRESENTANTES.ID = TREP_REGIAO.REP_ID
			   AND TEMPRESAS.ID = TPEDIDOS_VENDA.EMPR_ID
			   AND TDIVISOES_VENDAS.ID = TPEDIDOS_VENDA.DIVD_ID
			   AND TREP_HIERARQUIA.REP_ID = TREPRESENTANTES.ID
			   AND TREP_HIERARQUIA.REP_SUP_ID = TREPRESENTANTES_COORD.ID
			   AND TEMP_REP.REP_ID = TREPRESENTANTES.ID
			   AND TREPRESENTANTES_COORD.CAT_REP_ID  = TCAT_REP.ID
			   AND TTIPOS_NF.ID = TPEDIDOS_VENDA.TPNF_ID_DEFAULT
			   AND TPORTADORES.ID = TPEDIDOS_VENDA.POR_ID
			   AND TPEDIDOS_VENDA.POS_PDV = ''PE''
			   AND TPEDIDOS_VENDA.TIPO = ''PDV''
			   --AND TPEDIDOS_VENDA.SIT_PDV_COM = ''BLQ''
 			   AND EXISTS (SELECT 1
		                   FROM   FOCCO3I.TMOT_BLQ_PDV TMOT_BLQ_PDV
		                   WHERE  TMOT_BLQ_PDV.PDV_ID = TPEDIDOS_VENDA.ID
		                          AND TMOT_BLQ_PDV.TP_BLQ_PDV = ''PDV''
		                          AND TMOT_BLQ_PDV.IND_BLQ = ''V''
		                          AND TMOT_BLQ_PDV.DT_LIB IS NULL
		                          AND ROWNUM = 1
		                          AND TMOT_BLQ_PDV.TP_BLQ = ''COM'')
			   AND TEMP_REP.ATIVO = 1
			   AND TEMPRESAS.COD_EMP IN (' || PI_EMPRESA || ')';
			  
		IF PI_PEDIDO <> 0 THEN
			QUERY := QUERY || ' AND TPEDIDOS_VENDA.NUM_PEDIDO IN (' || PI_PEDIDO || ')';
		END IF;
			  
		IF PI_SITUACAOF <> 'T' THEN
		   QUERY := QUERY || ' AND TPEDIDOS_VENDA.SIT_PDV_FIN = ' || '''' || PI_SITUACAOF  || '''' || '';
		END IF;
	
		IF PI_SITUACAOC <> 'T' THEN
		   QUERY := QUERY || ' AND TPEDIDOS_VENDA.SIT_PDV_COM = ' || '''' || PI_SITUACAOC  || '''' || '';
		END IF;
	  
		IF PI_DIVISAO <> 0 THEN 
			QUERY := QUERY || ' AND TDIVISOES_VENDAS.ID IN ( SELECT DISTINCT ID FROM FOCCO3I.TDIVISOES_VENDAS DV WHERE COD_DIVD =' || PI_DIVISAO || ' AND EMPR_ID IN ( '|| PI_EMPRESA || '))';
		END IF;
	
	 	IF PI_REGIAO <> 0 THEN
	 	    QUERY := QUERY || ' AND TREGIOES.COD_REG = ' || PI_REGIAO || '';
	 	END IF;
	 
		IF PI_SUPERVISOR <> 0 THEN
		    QUERY := QUERY || ' AND TREPRESENTANTES_COORD.ID = ' || PI_SUPERVISOR || ' AND TCAT_REP.COD_CAT_REP = 4 ';
		END IF;
	
	
		 IF PI_REPRESENTANTE <> 0 THEN
		    QUERY := QUERY || ' AND TREPRESENTANTE.COD_REP = ' || PI_REPRESENTANTE || ''; 
		 END IF;
		
		QUERY := QUERY || '
			   GROUP BY TPEDIDOS_VENDA.ID,
 						TEMPRESAS.COD_EMP,
						TPEDIDOS_VENDA.SIT_PDV_FIN,
				 	    TPEDIDOS_VENDA.SIT_PDV_COM ,
				 	    TPEDIDOS_VENDA.NUM_PEDIDO,
						TCLIENTES.ID,
				 	    TCLIENTES.COD_CLI || '' - '' ||  TCLIENTES.DESCRICAO,
				 	    --NVL(otm_formata(TESTABELECIMENTOS.CNPJ,''CNPJ'',''F''),otm_formata(TESTABELECIMENTOS.CPF ,''CPF'',''F'')),
				 	    TESTABELECIMENTOS.CNPJ,
						TREPRESENTANTES.ID,
						TREPRESENTANTES.COD_REP || '' - '' || TREPRESENTANTES.DESCRICAO,
				 	    TCOND_PAGTOS.COD_CDPG||'' - ''||TCOND_PAGTOS.DESCRICAO,
						TPEDIDOS_VENDA.VLR_LIQ,
						TPEDIDOS_VENDA.DT_EMIS,
						TPEDIDOS_VENDA.DT_ENTREGA,
						TTIPOS_NF.COD_TP_NF || '' - '' || TTIPOS_NF.DESCRICAO ,
						TDIVISOES_VENDAS.ID,
						TTIPOS_NF.ID,
						TDIVISOES_VENDAS.DESCRICAO,
						TPEDIDOS_VENDA.TP_FRETE,
						TPORTADORES.ID,
						TPORTADORES.COD_POR || '' - '' || TPORTADORES.DESCRICAO,
						TPEDIDOS_VENDA.FIRME';
					
					
        QUERY := QUERY || ' UNION ALL SELECT ' || PI_SESSAO || ',
					TPEDIDOS_VENDA.ID,
 					TEMPRESAS.COD_EMP,
					TPEDIDOS_VENDA.SIT_PDV_FIN,
			 	    TPEDIDOS_VENDA.SIT_PDV_COM ,
			 	    TPEDIDOS_VENDA.NUM_PEDIDO,
					TCLIENTES.ID CLIENTE_ID,
			 	    TCLIENTES.COD_CLI || '' - '' || TCLIENTES.DESCRICAO CLIENTE,
			 	    --NVL(otm_formata(TESTABELECIMENTOS.CNPJ,''CNPJ'',''F''),otm_formata(TESTABELECIMENTOS.CPF ,''CPF'',''F'')) CNPJ_CPF,
					CASE 
						WHEN LENGTH(TESTABELECIMENTOS.CNPJ) < 14
							THEN LPAD(TO_CHAR( TESTABELECIMENTOS.CNPJ ),14,0)
						WHEN LENGTH(TESTABELECIMENTOS.CNPJ) >= 14
							THEN TO_CHAR(TESTABELECIMENTOS.CNPJ)
				    END AS CNPJ,
					TREPRESENTANTES.ID REP_ID,
			 	    TREPRESENTANTES.COD_REP || '' - '' || TREPRESENTANTES.DESCRICAO REPRESENTANTE,
			 	    TCOND_PAGTOS.COD_CDPG||'' - ''||TCOND_PAGTOS.DESCRICAO AS COND_PAGTO,
					TPEDIDOS_VENDA.VLR_LIQ VALOR_TOTAL,
					TPORTADORES.ID,
					TPORTADORES.COD_POR || '' - '' || TPORTADORES.DESCRICAO,
					''SUFRAMA'',
					''SIMPLES'',
					''ENDEREÇO'',
					TPEDIDOS_VENDA.DT_EMIS DATA_EMISSAO,
					TPEDIDOS_VENDA.DT_ENTREGA DATA_ENTREGA,
					DECODE(TPEDIDOS_VENDA.FIRME, 1, ''S'',0 , ''N'') AS FIRME,
					SYSDATE,
					TDIVISOES_VENDAS.ID,
					TDIVISOES_VENDAS.DESCRICAO "DIV_VENDA",
					TTIPOS_NF.ID,
					TTIPOS_NF.COD_TP_NF || '' - '' || TTIPOS_NF.DESCRICAO "TP_NF",
					TPEDIDOS_VENDA.TP_FRETE 
			  FROM FOCCO3I.TPEDIDOS_VENDA TPEDIDOS_VENDA,
			  	   FOCCO3I.TCLIENTES TCLIENTES,
			  	   FOCCO3I.TESTABELECIMENTOS TESTABELECIMENTOS,
			  	   FOCCO3I.TREPRESENTANTES TREPRESENTANTES,
			  	   FOCCO3I.TCOND_PAGTOS TCOND_PAGTOS,
			  	   FOCCO3I.TREGIOES TREGIOES,
			 	   FOCCO3I.TREP_REGIAO TREP_REGIAO,
			 	   FOCCO3I.TEMPRESAS TEMPRESAS,
			 	   FOCCO3I.TDIVISOES_VENDAS TDIVISOES_VENDAS,
				   FOCCO3I.TTIPOS_NF TTIPOS_NF,
				   FOCCO3I.TPORTADORES TPORTADORES 
			 WHERE TCLIENTES.ID = TPEDIDOS_VENDA.CLI_ID 
			   AND TCLIENTES.EST_ID_FAT = TESTABELECIMENTOS.ID
			   AND TREPRESENTANTES.ID = TPEDIDOS_VENDA.REP_ID
			   AND TPEDIDOS_VENDA.CDPG_ID = TCOND_PAGTOS.ID
			   AND TREGIOES.ID = TREP_REGIAO.REG_ID
			   AND TREPRESENTANTES.ID = TREP_REGIAO.REP_ID
			   AND TEMPRESAS.ID = TPEDIDOS_VENDA.EMPR_ID
			   AND TDIVISOES_VENDAS.ID = TPEDIDOS_VENDA.DIVD_ID
			   AND TTIPOS_NF.ID = TPEDIDOS_VENDA.TPNF_ID_DEFAULT
			   AND TPORTADORES.ID = TPEDIDOS_VENDA.POR_ID 
			   AND TPEDIDOS_VENDA.POS_PDV = ''PE''
			   AND TPEDIDOS_VENDA.TIPO = ''PDV''
			   --AND TPEDIDOS_VENDA.SIT_PDV_COM = ''BLQ''
					 			   AND EXISTS (SELECT 1
							                   FROM   FOCCO3I.TMOT_BLQ_PDV TMOT_BLQ_PDV
							                   WHERE  TMOT_BLQ_PDV.PDV_ID = TPEDIDOS_VENDA.ID
							                          AND TMOT_BLQ_PDV.TP_BLQ_PDV = ''PDV''
							                          AND TMOT_BLQ_PDV.IND_BLQ = ''V''
							                          AND TMOT_BLQ_PDV.DT_LIB IS NULL
							                          AND ROWNUM = 1
							                          AND TMOT_BLQ_PDV.TP_BLQ = ''COM'')
						           AND NOT EXISTS (
						           					SELECT 1 
						           					 FROM  	FOCCO3I.TREP_HIERARQUIA TREP_HIERARQUIA,
								 	     					FOCCO3I.TEMP_REP TEMP_REP,
								 	                        FOCCO3I.TREPRESENTANTES TREPRESENTANTES_COORD,
								 	   						FOCCO3I.TCAT_REP TCAT_REP
								 	   				 WHERE  TREP_HIERARQUIA.REP_ID = TREPRESENTANTES.ID
								   				       AND TREP_HIERARQUIA.REP_SUP_ID = TREPRESENTANTES_COORD.ID
								   					   AND TEMP_REP.REP_ID = TREPRESENTANTES.ID
								                       AND TREPRESENTANTES_COORD.CAT_REP_ID  = TCAT_REP.ID
								                       AND TEMP_REP.ATIVO = 1)
								   AND TEMPRESAS.COD_EMP IN (' || PI_EMPRESA || ')';

			IF PI_PEDIDO <> 0 THEN
				QUERY := QUERY || ' AND TPEDIDOS_VENDA.NUM_PEDIDO IN (' || PI_PEDIDO || ')';
			END IF;
				  
			IF PI_SITUACAOF <> 'T' THEN
			   QUERY := QUERY || ' AND TPEDIDOS_VENDA.SIT_PDV_FIN = ' || '''' || PI_SITUACAOF  || '''' || '';
			END IF;
		
			IF PI_SITUACAOC <> 'T' THEN
		   		QUERY := QUERY || ' AND TPEDIDOS_VENDA.SIT_PDV_COM = ' || '''' || PI_SITUACAOC  || '''' || '';
			END IF;
				  
			IF PI_DIVISAO <> 0 THEN 
				QUERY := QUERY || ' AND TDIVISOES_VENDAS.ID IN ( SELECT DISTINCT ID FROM FOCCO3I.TDIVISOES_VENDAS DV WHERE COD_DIVD =' || PI_DIVISAO || ' AND EMPR_ID IN ( '|| PI_EMPRESA || '))';
			END IF;
		
		 	IF PI_REGIAO <> 0 THEN
		 	    QUERY := QUERY || ' AND TREGIOES.COD_REG = ' || PI_REGIAO || '';
		 	END IF;
		 
		
		
			 IF PI_REPRESENTANTE <> 0 THEN
			    QUERY := QUERY || ' AND TREPRESENTANTE.COD_REP = ' || PI_REPRESENTANTE || ''; 
			 END IF;
									  
	QUERY := QUERY || '
			   GROUP BY TPEDIDOS_VENDA.ID,
 						TEMPRESAS.COD_EMP,
						TPEDIDOS_VENDA.SIT_PDV_FIN,
				 	    TPEDIDOS_VENDA.SIT_PDV_COM ,
				 	    TPEDIDOS_VENDA.NUM_PEDIDO,
						TCLIENTES.ID,
				 	    TCLIENTES.COD_CLI || '' - '' ||  TCLIENTES.DESCRICAO,
				 	    --NVL(otm_formata(TESTABELECIMENTOS.CNPJ,''CNPJ'',''F''),otm_formata(TESTABELECIMENTOS.CPF ,''CPF'',''F'')),
				 	    TESTABELECIMENTOS.CNPJ,
						TREPRESENTANTES.ID,
						TREPRESENTANTES.COD_REP || '' - '' || TREPRESENTANTES.DESCRICAO,
				 	    TCOND_PAGTOS.COD_CDPG||'' - ''||TCOND_PAGTOS.DESCRICAO,
						TPEDIDOS_VENDA.VLR_LIQ,
						TPEDIDOS_VENDA.DT_EMIS,
						TPEDIDOS_VENDA.DT_ENTREGA,
						TTIPOS_NF.COD_TP_NF || '' - '' || TTIPOS_NF.DESCRICAO ,
						TDIVISOES_VENDAS.DESCRICAO,
						TDIVISOES_VENDAS.ID,
						TTIPOS_NF.ID,
						TPORTADORES.ID,
						TPORTADORES.COD_POR || '' - '' || TPORTADORES.DESCRICAO,
						TPEDIDOS_VENDA.TP_FRETE,
						TPEDIDOS_VENDA.FIRME';				

	INSERT INTO SQL_TESTE(SQL_TESTE) VALUES (QUERY);
    COMMIT;
	
   	DELETE FROM TLIBERA_PDV_COM_OTM WHERE SESSAO = PI_SESSAO;
    COMMIT;
   
    EXECUTE IMMEDIATE ('INSERT INTO TLIBERA_PDV_COM_OTM ' || QUERY || '' );
    COMMIT;
   
END;

												 
			
